---
# --- Pool ---
- name: Check if storage-pool exists
  ansible.builtin.command: zpool list storage-pool
  register: zpool_check
  changed_when: false
  failed_when: false

- name: Create mirrored zfs pool
  ansible.builtin.command:
    argv:
      - zpool
      - create
      - -m
      - /mnt/storage
      - storage-pool
      - mirror
      - "/dev/disk/by-partuuid/{{ zfs_disk1_partuuid }}"
      - "/dev/disk/by-partuuid/{{ zfs_disk2_partuuid }}"
  when: zpool_check.rc != 0

# --- Dataset ---
- name: Create zfs dataset
  community.general.zfs:
    name: storage-pool/data
    state: present

- name: Set permissions for zfs dataset
  ansible.builtin.file:
    path: /mnt/storage/data
    owner: nas
    group: nas
    mode: '0755'
